### ISSUE TITLE
REI keybind conflict

### ISSUE THREAD

**Issue by tyreforhyred** [oitsjustjose/Harmonious-Engineering#10]
The keybind for REI's Show Uses is set to F, which by default is vanilla Minecraft's Offhand button. The conflict means that you cannot mouse over an item in your inventory and immediately put it in your offhand with the hotkey.

**Comment by oitsjustjose** [comment]
Ah woops - that's my personal preference and I didn't mean to leave that in. Thanks for the note!

**Comment by oitsjustjose** [comment]
Closing as REI is no longer included and this was fixed
