### ISSUE TITLE
Create bulk blasting returns wrong number of nuggets

### ISSUE THREAD

**Issue by Samrel556** [oitsjustjose/Harmonious-Engineering#13]
Harmonious Engineering version 3.1.9 on Minecraft 1.18.2

JEI states that Create's bulk blasting should return 4 nuggets from Raw Ore 

![JEIEntry2](https://user-images.githubusercontent.com/18405229/192408592-d6173c21-a584-4c67-b462-df5788d73709.png)

in practice only 3 nuggets come out.

![Input](https://user-images.githubusercontent.com/18405229/192408647-31ebbd3a-7c44-4462-aeac-2041ecf7143e.png)
![Output](https://user-images.githubusercontent.com/18405229/192408657-4911d3fa-4583-4ecb-88a4-e26c9b031b6d.png)

It would seem that Create itself is retrieving Furnace recipes and using them instead of Blast Furnace recipes in reality while JEI shows the Blast Furnace version.

Bulk Blasting setup just in case I'm being dumb.

![bulkBlastSetup](https://user-images.githubusercontent.com/18405229/192408780-e37934a4-f456-4f30-8a00-dabb8bbaad5e.png)

**Comment by oitsjustjose** [comment]
Unfortunately this is a bug with Create and is beyond my control - Create automatically picks up on *all* smelting recipes and assumes that the recipe can be done via Bulk Blasting unless the item has a Smoker recipe (i.e. it's a food) and sould then be Bulk Smoked. As such, it now has two blasting recipes to contend with: the one I specified as blasting-only, yielding 4 nuggets, and the smelting one which it automatically picked up on yielding 3.

I'd suggest filing a report [here](https://github.com/Creators-of-Create/Create/issues) and linking this bug. Marking as closed for now - sorry about the inconvenience!
