### ISSUE TITLE
Obtaining Zinc in the Early Game

### ISSUE THREAD

**Issue by Mdbgamer** [oitsjustjose/Harmonious-Engineering#8]
I seem to be having one small issue: I can't process iron without Create machines, but I can't make anything from Create without making the Andesite Alloy out of Zinc and Andesite, the former of which I need an _iron pickaxe_ to mine. 

Unless I've missed something, I was unable to obtain any form of progression until I killed an Iron Golem I found. >.>

**Comment by oitsjustjose** [comment]
Oh shoot you're completely right!! That slipped my mind entirely. I'm working on a fix for this now.

**Comment by oitsjustjose** [comment]
Fixed in [this update](https://www.curseforge.com/minecraft/modpacks/harmonious-engineering/files/3693480). Thank you!

**Comment by Mdbgamer** [comment]
You're not gonna believe this, but I think you've missed something else. 
I can't craft the tiny iron powder. xD
I feel bad, cuz pack dev isn't an easy occupation...

**Comment by oitsjustjose** [comment]
Nah I'd believe it. 2.1.5b has been released to fix this, should be public soon.

**Comment by Mdbgamer** [comment]
Awesome, lol. Glad I could catch these for ya.
