### ISSUE TITLE
(yes, another Zinc related issue xd) Finding enough Zinc to do anything

### ISSUE THREAD

**Issue by Mdbgamer** [oitsjustjose/Harmonious-Engineering#9]
I don't know if this is a result of an older model of world generation from a prior version of the pack, or if it's just me not doing something right, but it feels like Zinc is a lot more rare than other ores, especially Iron, Copper, and Tin. Especially as Zinc is required for Brass, it feels like there's not nearly enough without mining out entire chunks to gather it. 

Lemme know if I should do anything, or if I'm doing anything wrong here! XD

**Comment by Mdbgamer** [comment]
Sidenote: Will there be some way to obtain ores from, say, the void or something? Something like a void miner, or the modern version of the deep dark dimension.

**Comment by oitsjustjose** [comment]
I've been playtesting for a LONG while and never ran into this, even when really diving deep into Create which uses Zinc the most. Are you mining at the right heights for it?

**Comment by Mdbgamer** [comment]
It's been an age, my laptop I was playing this pack on died, and I don't remember. XD
